------------------------------------------------------------------------
-- Event:        SQL Saturday #777 Parma, November 24, 2018            -
-- Session:      SQL Server Query Optimizer end-to-end                 -
-- https://www.sqlsaturday.com/777/Sessions/Details.aspx?sid=79997     -
-- Demo:         Optimization process                                  -
-- Author:       Sergio Govoni                                         -
-- Notes:        --                                                    -
------------------------------------------------------------------------

USE [AdventureWorks2017];
GO

------------------------------------------------------------------------
-- The Optimization Process                                            -
------------------------------------------------------------------------


DBCC TRACEON(3604);

DBCC FREEPROCCACHE;
GO

-- TF 8675 will show optimization phases and search times
SELECT
  *
FROM
  Production.vw_Get_BillOfMaterials_Tree
WHERE
  [Path] LIKE '749%'
ORDER BY
  [Path]
OPTION (RECOMPILE, QUERYTRACEON 8675);
GO

/*
End of simplification, time: 0.005 net: 0.005 total: 0 net: 0.005

end exploration, tasks: 2332 no total cost time: 0.018 net: 0.018 total: 0 net: 0.023

end exploration, tasks: 5614 no total cost time: 0.017 net: 0.017 total: 0 net: 0.041

end search(0),  cost: 1.36269 tasks: 5806 time: 0.001 net: 0.001 total: 0 net: 0.042

*** Optimizer time out abort at task 5806 ***

End of post optimization rewrite, time: 0.001 net: 0.001 total: 0 net: 0.044

End of query plan compilation, time: 0.002 net: 0.002 total: 0 net: 0.046
*/



-- TF 8671 prevents the optimization process stopping due to a "Good Enough Plan found"
-- TF 8675 will show optimization phases and search times
SELECT
  *
FROM
  Production.vw_Get_BillOfMaterials_Tree
WHERE
  [Path] LIKE '749%'
ORDER BY
  [Path]
OPTION (RECOMPILE, QUERYTRACEON 8671, QUERYTRACEON 8675);
GO



/*
End of simplification, time: 0.005 net: 0.005 total: 0 net: 0.005

end exploration, tasks: 2332 no total cost time: 0.019 net: 0.019 total: 0 net: 0.024

end exploration, tasks: 5925 no total cost time: 0.018 net: 0.018 total: 0 net: 0.043

end search(0),  cost: 1.36269 tasks: 6053 time: 0.001 net: 0.001 total: 0 net: 0.044

*** Optimizer time out abort at task 6053 ***

End of post optimization rewrite, time: 0.001 net: 0.001 total: 0 net: 0.045

End of query plan compilation, time: 0.002 net: 0.002 total: 0 net: 0.047
*/



-- TF 8671 prevents the optimization process stopping due to a "Good Enough Plan found"
-- TF 8675 will show optimization phases and search times
-- TF 8780 gives "more time" to the Query Optimizer
SELECT
  *
FROM
  Production.vw_Get_BillOfMaterials_Tree
WHERE
  [Path] LIKE '749%'
ORDER BY
  [Path]
OPTION (RECOMPILE, QUERYTRACEON 8671, QUERYTRACEON 8675, QUERYTRACEON 8780);
GO

/*
End of simplification, time: 0.005 net: 0.005 total: 0 net: 0.005

end exploration, tasks: 2332 no total cost time: 0.017 net: 0.017 total: 0 net: 0.022

end exploration, tasks: 5925 no total cost time: 0.018 net: 0.018 total: 0 net: 0.04

end search(0),  cost: 1.36269 tasks: 6053 time: 0.002 net: 0.002 total: 0 net: 0.042

end exploration, tasks: 13014 Cost = 1.36269 time: 0.018 net: 0.018 total: 0 net: 0.061

end exploration, tasks: 30568 Cost = 1.36269 time: 0.068 net: 0.068 total: 0 net: 0.13

end search(1),  cost: 1.12074 tasks: 30864 time: 0.001 net: 0.001 total: 0 net: 0.132

end exploration, tasks: 69859 Cost = 1.12074 time: 0.136 net: 0.136 total: 0 net: 0.268

end exploration, tasks: 259844 Cost = 1.12074 time: 0.859 net: 0.859 total: 1 net: 1.128

end search(2),  cost: 1.12074 tasks: 259964 time: 0 net: 0 total: 1 net: 1.128

End of post optimization rewrite, time: 0.001 net: 0.001 total: 1 net: 1.13

End of query plan compilation, time: 0.002 net: 0.002 total: 1 net: 1.132
*/



------------------------------------------------------------------------
-- sys.dm_exec_query_optimizer_info                                    -
------------------------------------------------------------------------


-- Returns detailed statistics about the operation of the Query Optimizer
-- All values are cumulative since the system starts

-- You can use this DMV when tuning a workload to identify query optimization 
-- problems or improvements

-- counter = The name of the optimizer event
-- occurrence = The number of occurrences of the optimization event for this counter
-- value = The average value per event occurrence

SELECT * FROM sys.dm_exec_query_optimizer_info;
GO



-- Detailed statistics from the Query Optimizer

-- Thanks to the result of this CTE we can observe the percentage of trivial plan,
-- the percentage of plans generated by these phases: search 0, 1 and 2.

-- We can also observe the percentage of time-out, with time-out, I intend the end of the time
-- assigned to the optimization phases

WITH QO AS
(
  SELECT
    occurrence
  FROM
    sys.dm_exec_query_optimizer_info
  WHERE
    ([counter] = 'optimizations')
),
QOInfo AS
(
  SELECT
    [counter]
    ,[%] = CAST((occurrence * 100.00)/(SELECT occurrence FROM QO) AS DECIMAL(5, 2))
  FROM
    sys.dm_exec_query_optimizer_info
  WHERE
    [counter] IN (
                   'optimizations'
                   ,'trivial plan'
                   ,'no plan'
                   ,'search 0'
                   ,'search 1'
                   ,'search 2'
                   ,'timeout'
                   ,'memory limit exceeded'
                   ,'contains subquery'
                   ,'view reference'
                   ,'remote query'
                   ,'dynamic cursor request'
                   ,'fast forward cursor request'
	               )
)
SELECT
  [optimizations] AS [optimizations %]
  ,[trivial plan] AS [trivial plan %]
  ,[no plan] AS [no plan %]
  ,[search 0] AS [search 0 %]
  ,[search 1] AS [search 1 %]
  ,[search 2] AS [search 2 %]
  ,[timeout] AS [timeout %]
  ,[memory limit exceeded] AS [memory limit exceeded %]
  ,[contains subquery] AS [contains subquery %]
  ,[view reference] AS [view reference %]
  ,[remote query] AS [remote query %]
  ,[dynamic cursor request] AS [dynamic cursor request %]
  ,[fast forward cursor request] AS [fast forward cursor request %]
FROM
  QOInfo
PIVOT (MAX([%]) FOR [counter] 
  IN ([optimizations]
      ,[trivial plan]
      ,[no plan]
      ,[search 0]
      ,[search 1]
      ,[search 2]
      ,[timeout]
      ,[memory limit exceeded]
      ,[contains subquery]
      ,[view reference]
      ,[remote query]
      ,[dynamic cursor request]
      ,[fast forward cursor request])) AS p;
GO

-- What's this query for?
-- Its goal is to understand better the workload!


-- Extended events mapped values
SELECT
  *
FROM
  sys.dm_xe_map_values
WHERE
  (name Like '%optimizer%');
GO


USE [WideWorldImporters];
GO

------------------------------------------------------------------------
-- How to obtain information about the optimization                    -
-- applied to a particular query                                       -
------------------------------------------------------------------------

-- Because the DMV stores cumulative values since the SQL Server service
-- starts we must use the following technique:

-- 1) Saving optimization values in a particular moment
--    before the execution of the query we are focusing on
-- 2) Execute the query
-- 3) Another saving of the optimization values
-- 4) Make a SUBTRACTION of the values in step 1 and 3


-- To let the system know the query used in the first and third steps,
-- we have to execute them at the very beginning, discarding the results


DBCC FREEPROCCACHE;
GO

SELECT * INTO #optimizer_info_before_query FROM sys.dm_exec_query_optimizer_info;
GO

SELECT * INTO #optimizer_info_after_query FROM sys.dm_exec_query_optimizer_info;
GO

DROP TABLE #optimizer_info_before_query;
DROP TABLE #optimizer_info_after_query;
GO

SELECT * INTO #optimizer_info_before_query FROM sys.dm_exec_query_optimizer_info;
GO

-- 2. This query retrieves sales order starting from 01/01/2016
-- grouped by OrderID, ordered by total
SELECT
  h.OrderID
  ,SUM(d.UnitPrice * d.Quantity) AS LinesTotal
FROM
  Sales.Orders AS h
JOIN
  Sales.OrderLines AS d
  ON h.OrderID=d.OrderID
WHERE
  (h.OrderDate >= '20160101')
GROUP BY
  h.OrderID
ORDER BY
  LinesTotal DESC;
GO

SELECT * INTO #optimizer_info_after_query FROM sys.dm_exec_query_optimizer_info;
GO

-- SUBTRACTION of the values in step 1 and 3
SELECT
  a.counter
  ,occurrence = (a.occurrence - b.occurrence)
  ,value = ((a.occurrence * a.value) - (b.occurrence * b.value))
FROM
  #optimizer_info_before_query AS b
JOIN
  #optimizer_info_after_query AS a ON a.counter=b.counter
WHERE
  (a.occurrence <> b.occurrence);
GO

DROP TABLE #optimizer_info_before_query;
DROP TABLE #optimizer_info_after_query;
GO



------------------------------------------------------------------------
-- Transformation rules                                                -
------------------------------------------------------------------------

DBCC TRACEON(3604);
GO

-- 404 rules on SQL Server 2017
SELECT * FROM sys.dm_exec_query_transformation_stats;
GO

DBCC FREEPROCCACHE;
GO

SELECT * INTO #query_transformation_stats_before_query
FROM sys.dm_exec_query_transformation_stats;
GO

SELECT * INTO #query_transformation_stats_after_query
FROM sys.dm_exec_query_transformation_stats;
GO

DROP TABLE #query_transformation_stats_before_query;
DROP TABLE #query_transformation_stats_after_query;
GO


SELECT * INTO #query_transformation_stats_before_query
FROM sys.dm_exec_query_transformation_stats;
GO


SELECT
  P.FullName
  ,C.CustomerName
FROM
  Application.People AS P
JOIN
  Sales.Customers AS C ON C.PrimaryContactPersonID=P.PersonID
  OPTION (RECOMPILE, LOOP JOIN, MERGE JOIN)
--OPTION (RECOMPILE, QUERYTRACEON 8605, QUERYTRACEON 8606, QUERYTRACEON 8621)
GO

-- Query
-- 0,769501 with GbAggToHS ON
-- 2,48905  with GbAggToHS OFF
--SELECT
--  t.TerritoryID
--  ,COUNT(*)
--FROM
--  Sales.SalesTerritory AS t
--JOIN
--  Sales.SalesOrderHeader AS h ON h.TerritoryID=t.TerritoryID
--GROUP BY
--  t.TerritoryID;
--GO


--SELECT
--  P.FirstName
--  ,P.LastName
--  ,C.AccountNumber
--FROM
--  Person.Person AS P
--JOIN
--  Sales.Customer AS C ON C.PersonID = P.BusinessEntityID
----OPTION (RECOMPILE);
----OPTION (RECOMPILE, LOOP JOIN, MERGE JOIN);
--OPTION(RECOMPILE, QUERYRULEOFF JNtoHS, QUERYRULEOFF JNtoSM);


SELECT * INTO #query_transformation_stats_after_query
FROM sys.dm_exec_query_transformation_stats;
GO

SELECT
  a.name
  ,promised = (a.promised - b.promised)
FROM
  #query_transformation_stats_before_query AS b
JOIN
  #query_transformation_stats_after_query AS a ON a.name=b.name
WHERE
  (a.succeeded <> b.succeeded);
GO

DROP TABLE #query_transformation_stats_before_query;
DROP TABLE #query_transformation_stats_after_query;
GO


------------------------------------------------------------------------
-- Disable/Enable transformation rules                                 -
--                                                                     -
-- DBCC RULEON(), DBCC RULEOFF()                                       -
------------------------------------------------------------------------

DBCC RULEOFF('GbAggBeforeJoin');
DBCC RULEOFF('GbAggToStrm'); -- Group By Aggregate to
DBCC RULEOFF('JNtoHS')
GO

DBCC RULEON('GbAggBeforeJoin');
DBCC RULEON('GbAggToStrm'); -- Group By Aggregate to
DBCC RULEON('JNtoHS')
GO

DBCC SHOWOFFRULES;
GO

DBCC SHOWONRULES;
GO